export const mockOnlineCourses = [
    {
        id: 'course-ai-001',
        name: 'Nhập Môn Trí Tuệ Nhân Tạo (AI) và Học Máy',
        price: 1299000,
        image: '/images/course-ai-001.jpg',
        shortDesc: 'Tìm hiểu các khái niệm cơ bản về AI và Machine Learning.',
        longDesc: 'Khóa học này sẽ giới thiệu cho bạn thế giới rộng lớn của Trí tuệ Nhân tạo và Học máy. Bạn sẽ nắm vững các thuật toán cơ bản, ứng dụng thực tế và chuẩn bị nền tảng vững chắc cho hành trình AI của mình.',
        category: 'Khoa học dữ liệu & AI',
        level: 'Cơ bản',
        instructor: 'TS. Nguyễn Văn A',
        duration: '40 giờ học',
        rating: 4.8,
        reviews: 1250,
        isPopular: true,
        tags: ['AI', 'Machine Learning', 'Deep Learning', 'Python', 'Data Science'],
        prerequisites: ['Kiến thức lập trình cơ bản'],
    },
    {
        id: 'course-web-002',
        name: 'Phát Triển Web Fullstack với MERN Stack',
        price: 1899000,
        image: '/images/course-web-002.jpg',
        shortDesc: 'Xây dựng ứng dụng web hoàn chỉnh với MongoDB, Express, React, Node.js.',
        longDesc: 'Trở thành nhà phát triển Fullstack chuyên nghiệp với MERN Stack. Khóa học bao gồm việc xây dựng các dự án thực tế, từ frontend tương tác đến backend mạnh mẽ.',
        category: 'Phát triển Web',
        level: 'Nâng cao',
        instructor: 'Mr. Trần Thị B',
        duration: '60 giờ học',
        rating: 4.7,
        reviews: 980,
        isPopular: true,
        tags: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Fullstack', 'Web Development'],
        prerequisites: ['HTML, CSS, JavaScript cơ bản'],
    },
    {
        id: 'course-design-003',
        name: 'Thiết Kế Đồ Họa Chuyên Nghiệp với Adobe Photoshop & Illustrator',
        price: 1550000,
        image: '/images/course-design-003.jpg',
        shortDesc: 'Làm chủ các công cụ thiết kế hàng đầu của Adobe.',
        longDesc: 'Khóa học này sẽ đưa bạn từ người mới bắt đầu đến chuyên gia thiết kế đồ họa. Học cách tạo ra các ấn phẩm chuyên nghiệp, logo, poster và nhiều hơn nữa.',
        category: 'Thiết kế & Sáng tạo',
        level: 'Trung cấp',
        instructor: 'Ms. Lê Thị C',
        duration: '35 giờ học',
        rating: 4.6,
        reviews: 750,
        isPopular: false,
        tags: ['Graphic Design', 'Photoshop', 'Illustrator', 'UI/UX', 'Creativity'],
        prerequisites: ['Không yêu cầu'],
    },
    {
        id: 'course-lang-004',
        name: 'Luyện Thi IELTS Cấp Tốc: Kỹ Năng Speaking & Writing',
        price: 2500000,
        image: '/images/course-lang-004.jpg',
        shortDesc: 'Nâng cao band điểm IELTS Speaking và Writing.',
        longDesc: 'Khóa học chuyên sâu dành cho những ai muốn cải thiện nhanh chóng band điểm IELTS trong thời gian ngắn. Tập trung vào các chiến lược và mẹo làm bài hiệu quả.',
        category: 'Ngoại ngữ',
        level: 'Nâng cao',
        instructor: 'Cô Nguyễn Thị D',
        duration: '50 giờ học',
        rating: 4.9,
        reviews: 1500,
        isPopular: true,
        tags: ['IELTS', 'English', 'Speaking', 'Writing', 'Exam Preparation'],
        prerequisites: ['Trình độ tiếng Anh B1 trở lên'],
    },
    {
        id: 'course-data-005',
        name: 'Phân Tích Dữ Liệu với Python và Pandas',
        price: 1100000,
        image: '/images/course-data-005.jpg',
        shortDesc: 'Thực hành phân tích dữ liệu chuyên sâu với Python.',
        longDesc: 'Học cách làm sạch, xử lý, phân tích và trực quan hóa dữ liệu bằng thư viện Pandas và Matplotlib trong Python. Áp dụng vào các tình huống thực tế.',
        category: 'Khoa học dữ liệu & AI',
        level: 'Trung cấp',
        instructor: 'Mr. Phạm Văn E',
        duration: '30 giờ học',
        rating: 4.7,
        reviews: 890,
        isPopular: false,
        tags: ['Python', 'Data Analysis', 'Pandas', 'Visualization', 'Machine Learning'],
        prerequisites: ['Kiến thức Python cơ bản'],
    },
    {
        id: 'course-pm-006',
        name: 'Quản Lý Dự Án Theo Phương Pháp Agile & Scrum',
        price: 950000,
        image: '/images/course-pm-006.jpg',
        shortDesc: 'Áp dụng Agile và Scrum để quản lý dự án hiệu quả.',
        longDesc: 'Khóa học cung cấp kiến thức và kỹ năng thực hành về các phương pháp quản lý dự án linh hoạt Agile và Scrum, giúp bạn tối ưu hóa quy trình làm việc và sản phẩm.',
        category: 'Kinh doanh & Quản lý',
        level: 'Cơ bản',
        instructor: 'Chuyên gia Lê Văn G',
        duration: '25 giờ học',
        rating: 4.5,
        reviews: 620,
        isPopular: false,
        tags: ['Agile', 'Scrum', 'Project Management', 'Leadership', 'Teamwork'],
        prerequisites: ['Không yêu cầu'],
    },
    {
        id: 'course-market-007',
        name: 'Digital Marketing Toàn Diện: SEO, SEM, Social Media',
        price: 1400000,
        image: '/images/course-market-007.jpg',
        shortDesc: 'Xây dựng chiến lược marketing số hiệu quả cho doanh nghiệp.',
        longDesc: 'Khóa học bao gồm tất cả các khía cạnh của Digital Marketing, từ tối ưu hóa công cụ tìm kiếm (SEO) đến quảng cáo trên mạng xã hội và phân tích dữ liệu chiến dịch.',
        category: 'Marketing',
        level: 'Trung cấp',
        instructor: 'CEO Đỗ Thị H',
        duration: '45 giờ học',
        rating: 4.8,
        reviews: 1100,
        isPopular: true,
        tags: ['Digital Marketing', 'SEO', 'SEM', 'Social Media', 'Content Marketing'],
        prerequisites: ['Kiến thức marketing cơ bản'],
    },
    {
        id: 'course-finance-008',
        name: 'Đầu Tư Chứng Khoán Cơ Bản cho Người Mới',
        price: 850000,
        image: '/images/course-finance-008.jpg',
        shortDesc: 'Hướng dẫn các bước đầu tiên để tham gia thị trường chứng khoán.',
        longDesc: 'Tìm hiểu về các loại hình đầu tư, cách phân tích cơ bản và kỹ thuật, quản lý rủi ro và xây dựng danh mục đầu tư hiệu quả cho người mới bắt đầu.',
        category: 'Kinh doanh & Tài chính',
        level: 'Cơ bản',
        instructor: 'Chuyên gia Đặng Văn K',
        duration: '20 giờ học',
        rating: 4.6,
        reviews: 580,
        isPopular: false,
        tags: ['Investment', 'Stock Market', 'Finance', 'Trading', 'Personal Finance'],
        prerequisites: ['Không yêu cầu'],
    },
    {
        id: 'course-prog-009',
        name: 'Lập Trình Di Động với React Native',
        price: 1650000,
        image: '/images/course-prog-009.jpg',
        shortDesc: 'Xây dựng ứng dụng di động đa nền tảng cho iOS và Android.',
        longDesc: 'Học cách phát triển ứng dụng di động chất lượng cao chỉ với một mã nguồn duy nhất bằng React Native. Bao gồm các API thiết bị, quản lý state và triển khai ứng dụng.',
        category: 'Phát triển Phần mềm',
        level: 'Trung cấp',
        instructor: 'Mr. Bùi Văn L',
        duration: '55 giờ học',
        rating: 4.7,
        reviews: 720,
        isPopular: true,
        tags: ['React Native', 'Mobile Development', 'JavaScript', 'Cross Platform', 'iOS', 'Android'],
        prerequisites: ['Kiến thức ReactJS cơ bản'],
    },
    {
        id: 'course-cloud-010',
        name: 'DevOps và Điện Toán Đám Mây với AWS',
        price: 2100000,
        image: '/images/course-cloud-010.jpg',
        shortDesc: 'Triển khai và quản lý ứng dụng trên nền tảng AWS với DevOps.',
        longDesc: 'Khóa học chuyên sâu về DevOps, tích hợp liên tục/triển khai liên tục (CI/CD) và quản lý hạ tầng trên Amazon Web Services (AWS).',
        category: 'Điện toán đám mây & DevOps',
        level: 'Nâng cao',
        instructor: 'Kỹ sư Hồ Văn M',
        duration: '70 giờ học',
        rating: 4.9,
        reviews: 950,
        isPopular: true,
        tags: ['DevOps', 'AWS', 'Cloud', 'CI/CD', 'Docker', 'Kubernetes', 'Python'],
        prerequisites: ['Kiến thức Linux và mạng cơ bản'],
    },
    {
        id: 'course-language-011',
        name: 'Tiếng Nhật Giao Tiếp N2',
        price: 1900000,
        image: '/images/course-langague-011.png',
        shortDesc: 'Nâng cao khả năng giao tiếp và ngữ pháp tiếng Nhật để đạt N2.',
        longDesc: 'Khóa học được thiết kế cho những người đã có kiến thức tiếng Nhật cơ bản và muốn đạt trình độ N2. Tập trung vào ngữ pháp phức tạp, đọc hiểu và nghe hiểu.',
        category: 'Ngoại ngữ',
        level: 'Nâng cao',
        instructor: 'Cô Tanaka Yumi',
        duration: '80 giờ học',
        rating: 4.8,
        reviews: 680,
        isPopular: false,
        tags: ['Japanese', 'JLPT N2', 'Communication', 'Grammar', 'Speaking'],
        prerequisites: ['Trình độ tiếng Nhật N3'],
    },
    {
        id: 'course-excel-012',
        name: 'Excel Nâng Cao: Phân Tích Dữ Liệu và Báo Cáo',
        price: 650000,
        image: '/images/course-excel-012.jpg',
        shortDesc: 'Thành thạo các hàm nâng cao, PivotTable và VBA trong Excel.',
        longDesc: 'Khóa học này sẽ giúp bạn trở thành chuyên gia Excel, sử dụng các công cụ mạnh mẽ để phân tích dữ liệu, tạo báo cáo động và tự động hóa các tác vụ lặp lại.',
        category: 'Văn phòng & Công cụ',
        level: 'Nâng cao',
        instructor: 'Chuyên gia Nguyễn Thanh P',
        duration: '28 giờ học',
        rating: 4.7,
        reviews: 1050,
        isPopular: true,
        tags: ['Excel', 'Data Analysis', 'PivotTable', 'VBA', 'Reporting'],
        prerequisites: ['Kiến thức Excel cơ bản'],
    },
    {
        id: 'course-art-013',
        name: 'Vẽ Tranh Kỹ Thuật Số với Procreate',
        price: 790000,
        image: '/images/course-art-013.jpg',
        shortDesc: 'Học cách vẽ tranh kỹ thuật số sống động trên iPad với Procreate.',
        longDesc: 'Khóa học thực hành dành cho các nghệ sĩ và người yêu nghệ thuật muốn chuyển sang vẽ kỹ thuật số. Bao gồm các kỹ thuật tô màu, đổ bóng, và tạo hiệu ứng đặc biệt.',
        category: 'Thiết kế & Sáng tạo',
        level: 'Cơ bản',
        instructor: 'Họa sĩ Đặng Thúy Q',
        duration: '22 giờ học',
        rating: 4.5,
        reviews: 450,
        isPopular: false,
        tags: ['Digital Art', 'Procreate', 'Drawing', 'Design', 'iPad'],
        prerequisites: ['Không yêu cầu'],
    },
    {
        id: 'course-iot-014',
        name: 'Phát Triển Ứng Dụng IoT với Arduino và Raspberry Pi',
        price: 1750000,
        image: '/images/course-iot-014.jpg',
        shortDesc: 'Xây dựng các dự án IoT thực tế từ cơ bản đến nâng cao.',
        longDesc: 'Tìm hiểu về Internet of Things (IoT) thông qua việc xây dựng các dự án với Arduino và Raspberry Pi. Kết nối cảm biến, xử lý dữ liệu và điều khiển thiết bị từ xa.',
        category: 'Kỹ thuật & Công nghệ',
        level: 'Trung cấp',
        instructor: 'Kỹ sư Vũ Minh R',
        duration: '50 giờ học',
        rating: 4.7,
        reviews: 590,
        isPopular: false,
        tags: ['IoT', 'Arduino', 'Raspberry Pi', 'Embedded', 'Python', 'Electronics'],
        prerequisites: ['Kiến thức lập trình cơ bản (C/C++ hoặc Python)'],
    },
    {
        id: 'course-softskill-015',
        name: 'Kỹ Năng Thuyết Trình Ấn Tượng',
        price: 590000,
        image: '/images/course-softskill-015.png',
        shortDesc: 'Nâng cao khả năng thuyết trình, gây ấn tượng với khán giả.',
        longDesc: 'Học cách cấu trúc bài thuyết trình, sử dụng ngôn ngữ cơ thể, kiểm soát giọng nói và tương tác với khán giả để tạo ra những buổi thuyết trình thành công và đáng nhớ.',
        category: 'Kỹ năng mềm',
        level: 'Cơ bản',
        instructor: 'Chuyên gia Đào Tạo S',
        duration: '15 giờ học',
        rating: 4.6,
        reviews: 700,
        isPopular: true,
        tags: ['Presentation', 'Communication', 'Public Speaking', 'Soft Skills', 'Confidence'],
        prerequisites: ['Không yêu cầu'],
    },
];